name: converta
description: "Converta - Universal offline file converter for Windows."
publish_to: 'none'
version: 1.2.0

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^11.0.2
  window_manager: ^0.5.1
  ffi: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
